### ISSUE TITLE
Visual ssl with channels different than 3

### ISSUE THREAD

**Issue by ethancohen123** [lucidrains/x-clip#11]
Hi,
seems to be a bug when trying to use visual ssl with a different number of channel than 3 . I think the error came from the visual ssl type ~row 280 here: 

#send a mock image tensor to instantiate parameters
self.forward(torch.randn(1, 3, image_size, image_size))

**Comment by lucidrains** [comment]
@ethancohen123 Hi Ethan :wave: let me know if https://github.com/lucidrains/x-clip/commit/5cd3038e6da1edb72eaaf98e0d26cb446859a321 works

I'm actually not too sure if SimCLR and SimSiam works well with non RGB images, but there is no reason why it should not

**Comment by ethancohen123** [comment]
It works only for grayscale images, I tried with channels=5 (channels of my images ) and I get this error (I guess you added grayscale option only ?)
TypeError: Input image tensor permitted channel values are [3, 1], but found 5

Thanks :)

**Comment by lucidrains** [comment]
ohh that is pretty unconventional

let me know if https://github.com/lucidrains/x-clip/commit/d9c2c52f25bf8c1067637f10734d63fac88c27ca works!

**Comment by ethancohen123** [comment]
it works thank you !
