### ISSUE TITLE
Extract Text and Image Latents

### ISSUE THREAD

**Issue by mmsamiei** [lucidrains/x-clip#13]
Hi, in the current implementation we can only extract text and image embedding (by set return_encodings=True) which are obtained before applying latent linear layers. Isn't it better to add an option to extract latent embeddings? Another importance of this is that with the current code, it is impossible to extract the similarity matrix between a batch of images and a batch of text.

**Comment by lucidrains** [comment]
@mmsamiei Hi Mohammad! Try https://github.com/lucidrains/x-clip/commit/5eb5fcc10d574f7641e51444aa03f4e6ec8c42db#diff-3858fdc3d4b7a5fce034a5fe9f25bf300fe1431999316145c018015644e86f91R505

**Comment by mmsamiei** [comment]
Thanks a lot!
